### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by MazeChaZer** [halfzebra/create-elm-app#133]
I don't know if this is out of scope, but static typing for the JavaScript parts would be nice.

**Comment by halfzebra** [comment]
@MazeChaZer thanks for the suggestion! At the moment we are not considering introducing TypeScript to the project because it's mostly aimed for prototyping.

Please feel free to leave a comment or more suggestions!

For now, I'm closing this issue, feel free to reopen it if anything.

**Comment by screendriver** [comment]
TypeScript for the JavaScript part would be really awesome @halfzebra 😎

**Comment by ahstro** [comment]
Is this still not being considered? I imagine a lot of people using Elm would be interested in the possibility of using TypeScript (probably preferably without ejecting) and since both [`awesome-typescript-loader`](https://github.com/s-panferov/awesome-typescript-loader#transpileonly-boolean) and [`ts-loader`](https://github.com/TypeStrong/ts-loader#transpileonly-boolean-defaultfalse) support a `transpileOnly`-option to disable type checking, there's no need to force anyone to use anything but VanillaJS. I definitely thing this should be given another thought, both as a nice feature and in the context of #174.
