### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by mrrooijen** [halfzebra/create-elm-app#14]
Any chance you could add out-of-the-box SASS support?

Packages required:

- node-sass
- sass-loader

Webpack config:

```js
{
  test: /\.sass$/,
  loader: "style!css!sass?indentedSyntax"
}
```

**Comment by joakin** [comment]
In my opinion (for what it is worth) as the create-react-app did, this choices should be left for when you eject create-elm-app and continue configuring the project further with your choices.

Otherwise, the tool ends up bloated with sass, less, stylus, and a thousand other pre-set loaders as a reflection of people's personal choices.

I think this should be out of scope, but documentation about how to add sass, less, and other more advanced configurations once you eject would be great to have.

**Comment by kfrn** [comment]
+1 to @joakin's comment. Some info about how to add SASS would be really welcome.

**Comment by littleStudent** [comment]
if there is some interest in a Readme part that explains how to setup sass i could make a PR.
@halfzebra ?

**Comment by halfzebra** [comment]
@littleStudent that would be great!

I'm assuming it's not supposed to be very different from what [Create React App suggests](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)

I feel like this would make more sense than having SASS support included by default.
