### ISSUE TITLE
Consider lighter ES-to-JS solution

### ISSUE THREAD

**Issue by kylecordes** [halfzebra/create-elm-app#174]
I write this with some trepidation, is my suggestion in the post below can look pretty alien to people who been working with Babel for a while.

The basic gist is: the TypeScript compiler makes a great ES-to-JS compiler, even for projects which make no use whatsoever of TypeScript. It is fast, small, zero transitive dependencies, implements a broad swath of upcoming ES features that are for this through the standards process, and so on. 

http://kylecordes.com/2017/typescript-as-es2015-compiler

If the TypeScript compiler feels too alien for a non-TS project, then maybe something like Buble could achieve the same drastic reduction in installation footprint (due to in the p.m. transitive dependency package count in size):

https://buble.surge.sh/guide/

(I am a big fan of Babel - for projects that need and use its extensive configurability, plug-ins to craft a specific language subset to meet specific needs, and so on.)

**Comment by halfzebra** [comment]
Hello, @kylecordes! Thanks for contributing!

The size and a number of files are surely getting to the point when we should start thinking about reducing the size of the distribution.

Given that, I don't believe that TypeScript gives a good starting point for an Elm project. The mission of Create Elm App is to provide a minimal setup, which allows you to build and deploy your first app as fast as possible without thinking about the infrastructure too much.

Personally, I would prefer TypeScript in my Elm App instead of Vanilla/ES6,
but I'm afraid that Babel + "current" preset is the safest bet. :thinking: 

The only problem with Buble that I could foresee is that it's not the ES6 compiler most people want after ejecting.

I'm currently working on something, that will allow users have different kinds of setup after ejecting, but I wouldn't bet on TS/Buble as a default JavaScript compiler.

What do you think?

**Comment by kylecordes** [comment]
@halfzebra  Oh, I did not realize you had in mind user projects ever making use of JavaScript / Babel /  etc. aside from the small snippets people use to implement the JavaScript side of a Port. It's also interesting to see the attention to people who have ejected. I follow the CLI's for various frameworks libraries etc. that I use, and is most typical that their authors pay relatively little attention to those who eject, because the whole point of ejecting his be able to go make changes anyway. Very interesting.

In the long run I don't think it matters very much which tool is used - People working atop the JavaScript ecosystem have generally accepted that their tools are going to have transitive dependencies that bring in numerous files, and accommodated it with bought bigger hard drives and network connections. I don't think `create-elm-app` will gain or lose any users based on the Es6 compiler choice.

**Comment by gogocurtis** [comment]
I'm actually really on the fence about what create-elm-app does because of the use of babel and because of pulling in so many NPM dependencies.

**Comment by halfzebra** [comment]
I'm closing this due to the lack of activity.

With #280, we might consider not having ES6 by default and introduce it ass an opt-in plugin.

Please let us know if this makes sense and would make you reconsider Create Elm App.
