### ISSUE TITLE
Provide JS interoperation example

### ISSUE THREAD

**Issue by bigos** [halfzebra/create-elm-app#231]
Your script creates a different environment compared to JavaScript interoperation examples that I have looked at. Can you provide your own simple example that works with the JS and HTML that your script creates?

**Comment by bigos** [comment]
I have figured it out.
https://github.com/bigos/elm-counter/blob/290956f0666cb30c14edcf60a21ae550721d5140/src/index.js
but I still believe it should be better documented.

**Comment by bigos** [comment]
This is my suggestion. Please let me know what you think.
https://github.com/bigos/create-elm-app/commit/257fbdaa16f299432e9412c5f7fea3b20856e74d

**Comment by halfzebra** [comment]
Hello @bigos!

Thanks for raising this issue, you are right, it's not as straight-forward as the original example from Elm documentation because you have to be aware of ES6 modules.

I like your suggestion, but I also think it deserves a separate section in the documentation 🙂 

If you will move it into "JavaScript Interop", it could be a very nice addition to the docs!

**Comment by GAumala** [comment]
A "JavaScript Interop" section with ports example would be really nice! I think it would also be very helpful if it mentioned which ES6+ features are supported by the current configuration.

**Comment by bigos** [comment]
https://github.com/bigos/create-elm-app/blob/master/template/README.md#javascript-interop
Do you think it's ready for PR?

**Comment by halfzebra** [comment]
@bigos looks good to me!

Please feel free to create a PR 👍

**Comment by halfzebra** [comment]
#233 is merged, closing this!

Thanks for participating!
