### ISSUE TITLE
Skipping failed optional dependency ...  fsevents

### ISSUE THREAD

**Issue by MichaelHipp** [halfzebra/create-elm-app#24]
Got these when installing on Windows 10 x64:

`npm WARN optional Skipping failed optional dependency /create-elm-app/chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
`

Is 'fsevents' really optional? Do I lose any functionality?

I presume this is a Windows platform issue, there prolly should be something in the docs to warn folks about this.

**Comment by benbrandt** [comment]
@MichaelHipp this is a common warning in the npm ecosystem for Windows users. The warning for fsevents shows up in dependencies for React and a lot of other packages as well. As far as I know it's a package to monitor a specific Mac OS file system api, hence why it's an npm Warning rather than Error.

This isn't a direct dependency of create-elm-app, it's a dependency of another package, and as far as I am aware you aren't missing out on anything by not being able to install. I've never run into any issues due to this warning.

Hope that helps!

**Comment by MichaelHipp** [comment]
Thanks for the good explanation. I've been working with create-elm-app for a few hours now with no issues. Closing.
