### ISSUE TITLE
No hot reload on style changes

### ISSUE THREAD

**Issue by lolcookie** [halfzebra/create-elm-app#282]
### Is this a bug report?

No

### Environment

1. `node -v`: v6.10.2
2. `npm -v`: 6.2.0
3. `yarn --version` (if you use Yarn): 
4. `npm ls create-elm-app -g` (if you haven’t ejected): 2.0.0-rc2

Then, specify:

1. Operating system: MacOS
2. Browser and version (if relevant): 

### Steps to Reproduce

(Write your steps here:)

1. Create new elm app
2. `elm install mdgriffith/elm-ui`
3. Make a change to the style

### Expected Behavior

App should refresh and display the changed styles

### Actual Behavior

App rebuilds but styling does not change.

**Comment by halfzebra** [comment]
I'm afraid I can not reproduce this, there must be something that is missing from the report.

What type of Elm program are you running?
Are there errors in the browser's console?

**Comment by atlewee** [comment]
I have the same issue. No errors in console. It says "compiled in Debug mode" in console when ding changes.
But the browser has to be manually refreshed to see the change.
My program is "Browser.application"

I got automatic refresh working by removing the <div id="root"></div> in /public/index.html,
it will also work if you change the id in  index.js node: getElementById('**root**')  to some node that does not exist.

**Comment by halfzebra** [comment]
Hi @aaahrens, thanks for the feedback.

elm-css does not support HMR, the best you can do is watch changes and recompile as described [here](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#adding-a-css-preprocessor-sass-less-etc)

I'm closing this issue due to the lack of activity and minimal reproducible example. Please feel free to reopen or create a new one if it is possible to give us more info.
