### ISSUE TITLE
Let's talk about dead code elimination

### ISSUE THREAD

**Issue by andys8** [halfzebra/create-elm-app#314]
Since dead code elimination is one of the core features of elm 0.19. 
> Create Elm App comes with an opinionated setup for dead code elimination which is disabled by default, because it may break your code.

Does it make sense to disable dead-code elimination by default?

I guess `DEAD_CODE_ELIMINATION` is about the[ uglify settings](https://github.com/halfzebra/create-elm-app/blob/501673497a044e8e4cc0591ddbc6da7ec6d8cd0b/config/webpack.config.prod.js#L30-L54), but `elm-webpack-loader` would still set the `--optimize` flag.
Since the elm [documentation itself](https://elm-lang.org/0.19.0/optimize) describes how to run uglify, it should be pretty safe to enable the settings by default.

An alternative approach would integrate `elm-minify` which is implementing a webpack plugin. It's about adding a dependency, but maintaining less directly (in cases this will be improved in the future). In any way the implementation is interesting, since there are differences in the settings.
https://github.com/opvasger/elm-minify/blob/master/src/api.js

**Comment by halfzebra** [comment]
Hi @andys8, thanks for creating this issue!

I think the primary source of confusion is that the documentation was not yet updated to describe the changes of create-elm-app v2 #283. Before `0.19` it was possible to use UglifyJS for dead code elimination, but sometimes it broke th JavaScript, produced by Elm Compiler.

In my opinion, introducing `elm-minify` does not add any value, since we could inherit the config and enable it by default(if it's stable enough).

Here's what I can propose to solve this issue:
- Remove `DEAD_CODE_ELIMINATION` env variable
- Replace UglifyJS config with the one that could be used out of the box without any changes and disable Dead Code Elimination in UglifyJS
- Keep the `--optimize` flag enabled for the `elm-app build`

This would reduce the unnecessary configuration and provide a less confising build optimization setup.

How does that sound?

**Comment by andys8** [comment]
Sounds awesome!

**Comment by andys8** [comment]
I could look into getting a PR started, but I'm not familiar with Webpack plugins. Therefore I'm not confident in implementing the details of the second bullet point and making sure nothing broke.

**Comment by halfzebra** [comment]
I think they are referring to the UglifyJS configuration property called `passes`, which is responsible for running the optimizations more than one time.

If I'm not mistaken, the statement about increasing the number of passes is coming from the following discussion https://github.com/elm-community/elm-webpack-loader/pull/142#issuecomment-416568288

`UglifyJsPlugin` runs UglifyJS on the code and it is configured by passing the `uglifyOptions`. What we need is to pass the same options from `elm-minify`

**Comment by andys8** [comment]
Yeah, right. Thanks for the hint for the discussion about passes.

So there are two things:
1. Uglifyjs is called to compress with 1-3 passes (depending on who you refer to)
2. The compressed result is again put into uglifyjs with mangle options

A total of 2-4 runs. My comment above was targeting, how to run uglifyjs with different settings sequentially.

**Comment by halfzebra** [comment]
You are right, I did not check the code very carefully.

After looking into this for some time, I think it might be worth checking https://www.npmjs.com/package/terser-webpack-plugin instead of the UglifyJS plugin.

I suspect that it would be okay to use Terser with a single pass with `mangle` and `compress` options on.

Do you think it's worth running multiple passes?

**Comment by andys8** [comment]
The easiest approach would be to use the provided webpack plugin of `elm-minify` and measure the output size as reference for comparison. Afterwards we could use `UglifyWebpackPlugin` or `TerserWebpackPlugin` and compare if it's worth doing multiple passes (by hand or `passes` param).

> Do you think it's worth running multiple passes?
Can't speak for everybody, but to me the bytes saved by https://github.com/elm-community/elm-webpack-loader/pull/142#issuecomment-416568288 aren't worth the passes.

The more important part is the note in the elm docs, which suggests, that there is an issue, where standard ugligyjs (commandline) usage will not work as expected, which lead to the manually sequenced calls.

> Note 1: uglifyjs is called twice there. First to --compress and second to --mangle. This is necessary! Otherwise uglifyjs will ignore our pure_funcs flag.

**Comment by halfzebra** [comment]
Sounds fair 👍

**Comment by andys8** [comment]
@halfzebra Opened PR #315 :)

**Comment by halfzebra** [comment]
Thanks for your work, your PR has been released with the latest patch release.

Check it out! 🎉
