### ISSUE TITLE
How do I install a version to work with Elm 0.19

### ISSUE THREAD

**Issue by jpcharlesworth** [halfzebra/create-elm-app#368]
### Is this a bug report?

No

### Environment

1. `node -v`: 10.6.1
2. `npm -v`: 6.10.3
3. `yarn --version` (if you use Yarn): Not used
4. `npm ls create-elm-app -g` (if you haven’t ejected): -- create-elm-app@3.2.1

Then, specify:

1. Operating system: Wndows 10 with latest upgrades
2. Browser and version (if relevant): Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

### Steps to Reproduce

(Write your steps here:)

1. create-elm-app my-app
2. cd my-app
3. replace src/Main.elm by a valid elm version 0.19 file which imports Browser
4. elm-appstart

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by halfzebra** [comment]
Hello @jpcharlesworth!

Thanks for reaching out, the latest version of Create Elm App [uses Elm Compiler v0.19](https://github.com/halfzebra/create-elm-app/blob/master/package.json#L37), so I suspect there might be something else that causes your issue.

I'll close this issue for now, but please feel free to reopen it if you have further questions or comments.
Maybe it's a good idea to share the code that's causing the problem because the template uses [Browser stuff ](https://github.com/halfzebra/create-elm-app/blob/master/template/src/Main.elm#L3) out of the box.

Cheers!
