### ISSUE TITLE
Error on starting new application

### ISSUE THREAD

**Issue by Lodin** [halfzebra/create-elm-app#69]
By the command chain:
```bash
$ npm i -g create-elm-app
$ create-elm-app tst-elm
$ cd tst-elm
$ elm-app start
```
I am getting the following error:
```bash
Main.elm:3162 Uncaught ReferenceError: _elm_lang$virtual_dom$VirtualDom$programWithFlags is not defined
```
**OS**: Windows 10
**node**: v7.0.0
**npm**: 3.10.8

**Comment by halfzebra** [comment]
I have encountered this problem myself, somehow it is related to the new debug mode, the best I could think of for now is disabling the debugger by default and providing a flag for the `start` command for running the app in a normal mode.

Probably it's the same as #68

**Comment by briviere** [comment]
How do I disable the debugger?

thanks

Brian

**Comment by eezis** [comment]
I am a dangerous front-end noob but I found a way to make the app run. Delete the "elm-stuff" directory. Then "elm-app start" will compile and the app will run.

**Comment by colindensem** [comment]
Same issue, but on a clean-ish suse box. Confirm the delete elm-stuff solves the issue, but no root cause investigation made as yet. There is an additional 17.1 folder in the build-artifacts on initial launch.
` node -v; npm -v; elm -v
v7.1.0
3.10.9
0.18.0
`
Deleting elm-stuff is not an uncommon starting point. It's quick and painless :)

**Comment by halfzebra** [comment]
I think this one is not relevant at this point.

Please feel free to reopen the issue if you think that anything is missing.
