### ISSUE TITLE
Update to Webpack 2

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#71]
It's in beta but very stable - I've used it on numerous projects and not had issues; and it's not a huge amount of change.

Would you be happy with a PR if I found the time to make it? :)

**Comment by halfzebra** [comment]
@jackfranklin I'm using it myself, there are a couple reasons why Create Elm App does not rely on it yet.

First of all, it's [create-react-app/issues/183](https://github.com/facebookincubator/create-react-app/issues/183), on top of that we will won't get any benefits from tree-shaking.

Since [react-dev-utils/webpackHotDevClient](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js) is compatible with webpack 2.

I would give it a go 😃

**Comment by jackfranklin** [comment]
Do you mean that webpackHotDevClient isn't compatible with webpack 2, or that it is? Sorry; I'm a bit confused!

Maybe it is best to hold off for a bit; I might work on the PR anyway for when the time comes! :)

**Comment by halfzebra** [comment]
@jackfranklin Sorry, that was some wierd phrasing from me 😄 

webpackHotDevClient **is** compatible with webpack 2, it would be awesome if you gave it a shot at upgrading Create Elm App to use it!

**Comment by jackfranklin** [comment]
👍 I'll try to but if anyone beats me to it  I won't mind! :D

**Comment by jackfranklin** [comment]
@halfzebra going to revisit this soon now Webpack 2.2 is out as a beta. Just giving all the other Webpack packages time to catch up and then I'll get on this :)
